### ISSUE TITLE
New Tagged Release

### ISSUE THREAD

**Issue by liamoreilly** [dapphp/radius#16]
Hi,

There hasn't been a tagged release since 2018. This makes using this package a little more awkward than it should. For example, if using PHP >= 7.4 then composer.json must specify master or exact commit IDs to get newer code than the 'current release' (see commit cfea576545ddd801b6342f794f8fae2dab6654de). 

There have been many commits since 2018. Is it not time for a new tagged release?

Best,
Liam

**Comment by dapphp** [comment]
Indeed! Thank you for commenting.

Version 2.5.5 is now tagged and released to bring those older commits into a release and exclude PHP 8.0. Version 3.0 will be released to support PHP 7.3, 7.4, and 8.0+ using a newer phpunit version. 3.0 will also be more in line with the PHP requirements for librenms, one of this package's primary dependents.
