### ISSUE TITLE
[Feature request] multiple servers support

### ISSUE THREAD

**Issue by mneitsabes** [dapphp/radius#2]
Hello,

I am currently using your library which fulfills its role perfectly. I would like to know if you would be able to add support for multiple servers?

My network has two Network Policy Servers, one on each domain controller. Currently I have specified the primary NPS as the RADIUS server but this is a problem in the event when the DC1 goes down (failure or maintenance). The ideal would be to be able to specify several servers (in my case with the same secret) so the library can try to join at least a second server if the first one can not be reached.

What do you think of this idea ?

**Comment by dapphp** [comment]
It's a good idea.  In my environments, we have many RADIUS servers (for load balancing) and where the PHP code is in use, I take the approach of having the client code get the list of IPs and iterate over them trying each server until success or hard failure.

The only particular reason for this is because the code like this existed before I modernized SysCo code into what is now this library, and that library also only supported one server per object.

Seems like a reasonable thing to go in a future version.

Here are my examples:

    <?php

    // get a list of hosts that provide radius; the SRV record returns all possible radius hosts
    $hosts = dns_get_record('_radius._tcp.mydomain.com', DNS_ANY);

    // alternatively, you can use a regular DNS name with multiple A records
    $hosts = gethostbynamel('npsradius.yourdomain.com');

    // or, $hosts is just an array you've defined elsewhere.

    shuffle($hosts); // randomize order, if not returned in by precedence

    $radius = new \Dapphp\Radius\Radius();

    $radius->setSecret($radiusSharedSecret)
                ->setNasIPAddress($nasIP)
                ->setAttribute(32, $nasIdentifier)
                ->setAttribute(6, 8) /* authenticate only */
                ->setAttribute(31, $_SERVER['REMOTE_ADDR']);

    foreach($hosts as $host) {
        $server = $host['target']; // if using "dns_get_record" with SRV
        // otherwise
        $server = $host;

        $radius->setServer($server);

        $result = $radius->accessRequest($username, $password);

        if ($result === true) {
            break; // success
        } elseif ($radius->getErrorCode() === $radius::TYPE_ACCESS_REJECT) {
            break; // failure, bad credentials
        } else { /* likely a timeout; try next host */ }
    }

    if ($result === true) {
        // handle success
    } else {
        // login failed due to bad credentials, or all servers down
    }

**Comment by mneitsabes** [comment]
Thank you for your response and your code. I'll do this in the meantime.

**Comment by dapphp** [comment]
This feature is now available in release 2.5.3 using the methods [`accessRequestList`](https://github.com/dapphp/radius/blob/2.5.3/src/Radius.php#L1076) (for PAP, CHAP, MSCHAP-v1) and [`accessRequestEapMsChapV2List`](https://github.com/dapphp/radius/blob/2.5.3/src/Radius.php#L1300) (for EAP-MSCHAP v2).

To use it, build up the Radius object with your necessary attributes and then call the method as you were before, passing an array of hosts/IP's as the first argument:

    $radius = new \Dapphp\Radius\Radius();
    $radius->setSecret('radius shared secret')
           ->setNasIpAddress('10.0.1.2') // NAS server address
           ->setAttribute(6, 8) // example Service-Type
           ->setAttribute(32, 'login');  // NAS identifier

    $servers = [ 'rad-1.domain.local', 'rad-2.domain.local', 'rad-backup.domain.remote' ];
    // or using DNS
    $servers = gethostbynamel('radius.domain.org');

    $authenticated = $radius->accessRequestList($servers, $username, $password);

    if ($authenticated) {
        // auth success
    } elseif ($radius->getErrorCode() == \Dapphp\Radius\Radius::TYPE_ACCESS_REJECT) {
        // auth failed
    } else {
        // auth error
    }
