### ISSUE TITLE
Supplant PEAR_Chap dependency

### ISSUE THREAD

**Issue by dapphp** [dapphp/radius#3]
The included PEAR_Chap library uses `mcrypt` which is deprecated as of PHP 7.1.

Come up with an alternative that uses OpenSSL or the minimal requirements from something like phpseclib or other userland library.

**Comment by jklamcnt** [comment]
I replaced mcrypt with openssl.

```
    protected function _challengeResponse($lm = false)
    {
        if ($lm) {
            $hash = $this->lmPasswordHash();
        } else {
            $hash = $this->ntPasswordHash();
        }
        $hash = str_pad($hash, 21, "\0");

        $key = $this->_desAddParity(substr($hash, 0, 7));
        $resp1 = openssl_encrypt($this->challenge, 'des-ecb', $key, OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING);

        $key = $this->_desAddParity(substr($hash, 7, 7));
        $resp2 = openssl_encrypt($this->challenge, 'des-ecb', $key, OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING);

        $key = $this->_desAddParity(substr($hash, 14, 7));
        $resp3 = openssl_encrypt($this->challenge, 'des-ecb', $key, OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING);

        return $resp1 . $resp2 . $resp3;
    }
        
    private function _desHash($plain)
    {
        $key = $this->_desAddParity($plain);
        $hash = openssl_encrypt('KGS!@#$%', 'des-ecb', $key, OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING);
        return hash;
    }
```

**Comment by dapphp** [comment]
@jklamcnt  Thanks for the code!  I've committed the changes and will release shortly.

**Comment by meinemitternacht** [comment]
@dapphp Were you still planning on making a versioned release with these changes?  In order to use PHP 7.2 with this library in my project, I am using the dev-master version manually with composer.

**Comment by dapphp** [comment]
Hi @meinemitternacht,

Sorry about that.  I was hoping to squeeze in feature, #2 but haven't settled on how.

I've just tagged and pushed 2.5.2 so you can once again refer to a proper version.

Thanks for pointing that out.  If you run into any issues with 7.2 and the new code please reply or post back with a new issue.

**Comment by meinemitternacht** [comment]
@dapphp  It's not a problem! Thank you for taking the time to do that, and hope you have a great day!
